name = "airaquas-api-public"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  "airaquas.hair/fenzhen*",
  "airaquas.hair/guide*",
  "airaquas.hair/research*",
  "airaquas.hair/sebderm*",
]
