name = "airaquas-api-public"
main = "src/index.ts"
compatibility_date = "2024-12-01"

routes = [
  "airaquas.hair/fenzhen*",
  "airaquas.hair/guide*", 
  "airaquas.hair/research*",
  "airaquas.hair/sebderm*",
  "airaquas.hair/api/generate-poster",
]
