name = "airaquas-platform"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  "airaquas.hair/",
  "airaquas.hair/fenzhen*",
  "airaquas.hair/guide*",
  "airaquas.hair/research*",
  "airaquas.hair/detect*",
  "airaquas.hair/diagnosis*",
  "airaquas.hair/login",
  "airaquas.hair/members",
  "airaquas.hair/orders",
  "airaquas.hair/inventory",
  "airaquas.hair/marketing",
  "airaquas.hair/profit",
  "airaquas.hair/sebderm*",
  "airaquas.hair/postpartum*",
  "airaquas.hair/seasonal*",
  "airaquas.hair/dandruff*",
  "airaquas.hair/folliculitis*",
]
