name = "airaquas-api-community"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "airaquas-hair"
database_id = "aaccdbdb-1592-41dd-b906-891d0a9a9556"
