// Auto-generated by gen_salon_pages.py
// 78 cities, 92036 total shops

interface CityInfo {
  name: string;
  count: number;
  districts: { name: string; count: number }[];
}

export const CITIES: Record<string, CityInfo> = {
  "cd-salon-tony": {
    name: "\u6210\u90fd",
    count: 4020,
    districts: [{ name: "\u6b66\u4faf\u533a", count: 512 }, { name: "\u6210\u534e\u533a", count: 448 }, { name: "\u9526\u6c5f\u533a", count: 416 }, { name: "\u9752\u7f8a\u533a", count: 382 }, { name: "\u91d1\u725b\u533a", count: 376 }, { name: "\u9f99\u6cc9\u9a7f\u533a", count: 268 }, { name: "\u53cc\u6d41\u533a", count: 254 }, { name: "\u90eb\u90fd\u533a", count: 212 }, { name: "\u65b0\u90fd\u533a", count: 196 }, { name: "\u6e29\u6c5f\u533a", count: 172 }, { name: "\u5929\u5e9c\u65b0\u533a", count: 156 }, { name: "\u9752\u767d\u6c5f\u533a", count: 98 }, { name: "\u90fd\u6c5f\u5830\u5e02", count: 72 }, { name: "\u909b\u5d03\u5e02", count: 58 }, { name: "\u91d1\u5802\u53bf", count: 52 }],
  },
  "cq-salon-tony": {
    name: "\u91cd\u5e86",
    count: 3060,
    districts: [{ name: "\u6e1d\u5317\u533a", count: 412 }, { name: "\u6c99\u576a\u575d\u533a", count: 356 }, { name: "\u4e5d\u9f99\u5761\u533a", count: 328 }, { name: "\u6c5f\u5317\u533a", count: 286 }, { name: "\u5357\u5cb8\u533a", count: 274 }, { name: "\u6e1d\u4e2d\u533a", count: 242 }, { name: "\u5df4\u5357\u533a", count: 218 }, { name: "\u5927\u6e21\u53e3\u533a", count: 168 }, { name: "\u5317\u789a\u533a", count: 142 }, { name: "\u6daa\u9675\u533a", count: 108 }, { name: "\u4e07\u5dde\u533a", count: 86 }, { name: "\u6c38\u5ddd\u533a", count: 72 }, { name: "\u5408\u5ddd\u533a", count: 58 }],
  },
  "wh-salon-tony": {
    name: "\u6b66\u6c49",
    count: 2899,
    districts: [{ name: "\u6d2a\u5c71\u533a", count: 386 }, { name: "\u6b66\u660c\u533a", count: 352 }, { name: "\u6c5f\u5cb8\u533a", count: 298 }, { name: "\u6c49\u9633\u533a", count: 264 }, { name: "\u6c5f\u6c49\u533a", count: 246 }, { name: "\u785a\u53e3\u533a", count: 218 }, { name: "\u9752\u5c71\u533a", count: 186 }, { name: "\u4e1c\u897f\u6e56\u533a", count: 168 }, { name: "\u6c5f\u590f\u533a", count: 152 }, { name: "\u9ec4\u9642\u533a", count: 128 }, { name: "\u8521\u7538\u533a", count: 104 }, { name: "\u65b0\u6d32\u533a", count: 68 }, { name: "\u6c49\u5357\u533a", count: 42 }],
  },
  "hz-salon-tony": {
    name: "\u676d\u5dde",
    count: 2777,
    districts: [{ name: "\u4f59\u676d\u533a", count: 368 }, { name: "\u8427\u5c71\u533a", count: 342 }, { name: "\u897f\u6e56\u533a", count: 296 }, { name: "\u4e0a\u57ce\u533a", count: 268 }, { name: "\u62f1\u5885\u533a", count: 254 }, { name: "\u6ee8\u6c5f\u533a", count: 206 }, { name: "\u4e34\u5e73\u533a", count: 182 }, { name: "\u5bcc\u9633\u533a", count: 144 }, { name: "\u94b1\u5858\u533a", count: 126 }, { name: "\u4e34\u5b89\u533a", count: 108 }, { name: "\u6850\u5e90\u53bf", count: 58 }, { name: "\u5efa\u5fb7\u5e02", count: 42 }, { name: "\u6df3\u5b89\u53bf", count: 28 }],
  },
  "nj-salon-tony": {
    name: "\u5357\u4eac",
    count: 2323,
    districts: [{ name: "\u6c5f\u5b81\u533a", count: 342 }, { name: "\u9f13\u697c\u533a", count: 286 }, { name: "\u79e6\u6dee\u533a", count: 268 }, { name: "\u6816\u971e\u533a", count: 234 }, { name: "\u7384\u6b66\u533a", count: 216 }, { name: "\u5efa\u90ba\u533a", count: 198 }, { name: "\u96e8\u82b1\u53f0\u533a", count: 172 }, { name: "\u6d66\u53e3\u533a", count: 156 }, { name: "\u516d\u5408\u533a", count: 126 }, { name: "\u6ea7\u6c34\u533a", count: 86 }, { name: "\u9ad8\u6df3\u533a", count: 52 }],
  },
  "bj-salon-tony": {
    name: "\u5317\u4eac",
    count: 2193,
    districts: [{ name: "\u671d\u9633\u533a", count: 446 }, { name: "\u6d77\u6dc0\u533a", count: 352 }, { name: "\u4e30\u53f0\u533a", count: 246 }, { name: "\u5927\u5174\u533a", count: 185 }, { name: "\u901a\u5dde\u533a", count: 172 }, { name: "\u897f\u57ce\u533a", count: 155 }, { name: "\u4e1c\u57ce\u533a", count: 138 }, { name: "\u660c\u5e73\u533a", count: 126 }, { name: "\u987a\u4e49\u533a", count: 108 }, { name: "\u623f\u5c71\u533a", count: 96 }, { name: "\u77f3\u666f\u5c71\u533a", count: 72 }, { name: "\u5bc6\u4e91\u533a", count: 48 }, { name: "\u6000\u67d4\u533a", count: 32 }, { name: "\u95e8\u5934\u6c9f\u533a", count: 28 }, { name: "\u5e73\u8c37\u533a", count: 22 }, { name: "\u5ef6\u5e86\u533a", count: 18 }],
  },
  "sh-salon-tony": {
    name: "\u4e0a\u6d77",
    count: 2184,
    districts: [{ name: "\u6d66\u4e1c\u65b0\u533a", count: 412 }, { name: "\u95f5\u884c\u533a", count: 238 }, { name: "\u5b9d\u5c71\u533a", count: 196 }, { name: "\u5f90\u6c47\u533a", count: 172 }, { name: "\u6768\u6d66\u533a", count: 155 }, { name: "\u9759\u5b89\u533a", count: 148 }, { name: "\u666e\u9640\u533a", count: 137 }, { name: "\u957f\u5b81\u533a", count: 124 }, { name: "\u8679\u53e3\u533a", count: 108 }, { name: "\u677e\u6c5f\u533a", count: 104 }, { name: "\u5609\u5b9a\u533a", count: 98 }, { name: "\u9ec4\u6d66\u533a", count: 92 }, { name: "\u5949\u8d24\u533a", count: 60 }, { name: "\u9752\u6d66\u533a", count: 58 }, { name: "\u5d07\u660e\u533a", count: 42 }, { name: "\u91d1\u5c71\u533a", count: 40 }],
  },
  "qd-salon-tony": {
    name: "\u9752\u5c9b",
    count: 2156,
    districts: [{ name: "\u5e02\u5357\u533a", count: 312 }, { name: "\u5e02\u5317\u533a", count: 286 }, { name: "\u674e\u6ca7\u533a", count: 248 }, { name: "\u5d02\u5c71\u533a", count: 212 }, { name: "\u9ec4\u5c9b\u533a", count: 186 }, { name: "\u57ce\u9633\u533a", count: 156 }, { name: "\u5373\u58a8\u533a", count: 126 }, { name: "\u80f6\u5dde\u5e02", count: 68 }],
  },
  "heb-salon-tony": {
    name: "\u54c8\u5c14\u6ee8",
    count: 2112,
    districts: [{ name: "\u5357\u5c97\u533a", count: 368 }, { name: "\u9053\u91cc\u533a", count: 286 }, { name: "\u9999\u574a\u533a", count: 254 }, { name: "\u9053\u5916\u533a", count: 232 }, { name: "\u677e\u5317\u533a", count: 186 }, { name: "\u547c\u5170\u533a", count: 142 }, { name: "\u5e73\u623f\u533a", count: 98 }, { name: "\u963f\u57ce\u533a", count: 86 }, { name: "\u53cc\u57ce\u533a", count: 68 }],
  },
  "xa-salon-tony": {
    name: "\u897f\u5b89",
    count: 2069,
    districts: [{ name: "\u96c1\u5854\u533a", count: 346 }, { name: "\u672a\u592e\u533a", count: 298 }, { name: "\u7891\u6797\u533a", count: 232 }, { name: "\u83b2\u6e56\u533a", count: 218 }, { name: "\u957f\u5b89\u533a", count: 206 }, { name: "\u65b0\u57ce\u533a", count: 168 }, { name: "\u705e\u6865\u533a", count: 142 }, { name: "\u9ad8\u65b0\u533a", count: 128 }, { name: "\u960e\u826f\u533a", count: 56 }, { name: "\u4e34\u6f7c\u533a", count: 48 }],
  },
  "gzhu-salon-tony": {
    name: "\u5e7f\u5dde",
    count: 1955,
    districts: [{ name: "\u5929\u6cb3\u533a", count: 286 }, { name: "\u767d\u4e91\u533a", count: 264 }, { name: "\u756a\u79ba\u533a", count: 238 }, { name: "\u6d77\u73e0\u533a", count: 212 }, { name: "\u8d8a\u79c0\u533a", count: 188 }, { name: "\u82b1\u90fd\u533a", count: 156 }, { name: "\u9ec4\u57d4\u533a", count: 142 }, { name: "\u5357\u6c99\u533a", count: 98 }, { name: "\u8354\u6e7e\u533a", count: 96 }, { name: "\u589e\u57ce\u533a", count: 88 }, { name: "\u4ece\u5316\u533a", count: 64 }],
  },
  "gl-salon-tony": {
    name: "\u6842\u6797",
    count: 1945,
    districts: [{ name: "\u79c0\u5cf0\u533a", count: 186 }, { name: "\u8c61\u5c71\u533a", count: 168 }, { name: "\u4e03\u661f\u533a", count: 154 }, { name: "\u53e0\u5f69\u533a", count: 126 }, { name: "\u96c1\u5c71\u533a", count: 98 }, { name: "\u4e34\u6842\u533a", count: 86 }, { name: "\u9633\u6714\u53bf", count: 42 }],
  },
  "jn-salon-tony": {
    name: "\u6d4e\u5357",
    count: 1856,
    districts: [{ name: "\u5386\u4e0b\u533a", count: 286 }, { name: "\u5e02\u4e2d\u533a", count: 248 }, { name: "\u69d0\u836b\u533a", count: 212 }, { name: "\u5929\u6865\u533a", count: 186 }, { name: "\u5386\u57ce\u533a", count: 168 }, { name: "\u957f\u6e05\u533a", count: 96 }, { name: "\u7ae0\u4e18\u533a", count: 84 }],
  },
  "nb-salon-tony": {
    name: "\u5b81\u6ce2",
    count: 1756,
    districts: [{ name: "\u6d77\u66d9\u533a", count: 268 }, { name: "\u911e\u5dde\u533a", count: 242 }, { name: "\u6c5f\u5317\u533a", count: 196 }, { name: "\u9547\u6d77\u533a", count: 168 }, { name: "\u5317\u4ed1\u533a", count: 142 }, { name: "\u5949\u5316\u533a", count: 86 }, { name: "\u4f59\u59da\u5e02", count: 72 }, { name: "\u6148\u6eaa\u5e02", count: 68 }],
  },
  "dl-salon-tony": {
    name: "\u5927\u8fde",
    count: 1689,
    districts: [{ name: "\u4e2d\u5c71\u533a", count: 246 }, { name: "\u897f\u5c97\u533a", count: 218 }, { name: "\u6c99\u6cb3\u53e3\u533a", count: 196 }, { name: "\u7518\u4e95\u5b50\u533a", count: 168 }, { name: "\u65c5\u987a\u53e3\u533a", count: 96 }, { name: "\u91d1\u5dde\u533a", count: 86 }, { name: "\u74e6\u623f\u5e97\u5e02", count: 54 }],
  },
  "dg-salon-tony": {
    name: "\u4e1c\u839e",
    count: 1689,
    districts: [{ name: "\u5357\u57ce\u8857\u9053", count: 186 }, { name: "\u4e1c\u57ce\u8857\u9053", count: 168 }, { name: "\u957f\u5b89\u9547", count: 142 }, { name: "\u864e\u95e8\u9547", count: 128 }, { name: "\u539a\u8857\u9547", count: 96 }],
  },
  "su-salon-tony": {
    name: "\u82cf\u5dde",
    count: 1687,
    districts: [{ name: "\u5434\u4e2d\u533a", count: 268 }, { name: "\u6606\u5c71\u5e02", count: 246 }, { name: "\u5f20\u5bb6\u6e2f\u5e02", count: 212 }, { name: "\u59d1\u82cf\u533a", count: 198 }, { name: "\u864e\u4e18\u533a", count: 172 }, { name: "\u5434\u6c5f\u533a", count: 156 }, { name: "\u5e38\u719f\u5e02", count: 144 }, { name: "\u592a\u4ed3\u5e02", count: 108 }, { name: "\u76f8\u57ce\u533a", count: 96 }, { name: "\u5de5\u4e1a\u56ed\u533a", count: 87 }],
  },
  "km-salon-tony": {
    name: "\u6606\u660e",
    count: 1678,
    districts: [{ name: "\u4e94\u534e\u533a", count: 246 }, { name: "\u76d8\u9f99\u533a", count: 218 }, { name: "\u5b98\u6e21\u533a", count: 196 }, { name: "\u897f\u5c71\u533a", count: 168 }, { name: "\u5448\u8d21\u533a", count: 96 }, { name: "\u5b89\u5b81\u5e02", count: 72 }],
  },
  "hf-salon-tony": {
    name: "\u5408\u80a5",
    count: 1568,
    districts: [{ name: "\u8700\u5c71\u533a", count: 286 }, { name: "\u5305\u6cb3\u533a", count: 248 }, { name: "\u5e90\u9633\u533a", count: 212 }, { name: "\u7476\u6d77\u533a", count: 186 }, { name: "\u7ecf\u5f00\u533a", count: 126 }, { name: "\u80a5\u897f\u53bf", count: 86 }, { name: "\u957f\u4e30\u53bf", count: 58 }],
  },
  "zunyi-salon-tony": {
    name: "\u9075\u4e49",
    count: 1568,
    districts: [{ name: "\u7ea2\u82b1\u5c97\u533a", count: 196 }, { name: "\u6c47\u5ddd\u533a", count: 168 }, { name: "\u64ad\u5dde\u533a", count: 142 }, { name: "\u4ec1\u6000\u5e02", count: 96 }],
  },
  "szhen-salon-tony": {
    name: "\u6df1\u5733",
    count: 1524,
    districts: [{ name: "\u9f99\u5c97\u533a", count: 292 }, { name: "\u5b9d\u5b89\u533a", count: 268 }, { name: "\u9f99\u534e\u533a", count: 212 }, { name: "\u5357\u5c71\u533a", count: 198 }, { name: "\u798f\u7530\u533a", count: 176 }, { name: "\u7f57\u6e56\u533a", count: 132 }, { name: "\u5149\u660e\u533a", count: 88 }, { name: "\u576a\u5c71\u533a", count: 56 }, { name: "\u76d0\u7530\u533a", count: 42 }, { name: "\u5927\u9e4f\u65b0\u533a", count: 30 }],
  },
  "nn-salon-tony": {
    name: "\u5357\u5b81",
    count: 1482,
    districts: [{ name: "\u9752\u79c0\u533a", count: 268 }, { name: "\u5174\u5b81\u533a", count: 212 }, { name: "\u6c5f\u5357\u533a", count: 186 }, { name: "\u897f\u4e61\u5858\u533a", count: 168 }, { name: "\u826f\u5e86\u533a", count: 142 }, { name: "\u9095\u5b81\u533a", count: 86 }, { name: "\u6b66\u9e23\u533a", count: 72 }],
  },
  "zz-salon-tony": {
    name: "\u90d1\u5dde",
    count: 1456,
    districts: [{ name: "\u91d1\u6c34\u533a", count: 312 }, { name: "\u4e2d\u539f\u533a", count: 228 }, { name: "\u4e8c\u4e03\u533a", count: 198 }, { name: "\u7ba1\u57ce\u56de\u65cf\u533a", count: 168 }, { name: "\u90d1\u4e1c\u65b0\u533a", count: 146 }, { name: "\u60e0\u6d4e\u533a", count: 112 }, { name: "\u4e0a\u8857\u533a", count: 56 }, { name: "\u8365\u9633\u5e02", count: 44 }, { name: "\u65b0\u90d1\u5e02", count: 38 }, { name: "\u5de9\u4e49\u5e02", count: 28 }],
  },
  "cc-salon-tony": {
    name: "\u957f\u6625",
    count: 1456,
    districts: [{ name: "\u671d\u9633\u533a", count: 268 }, { name: "\u5357\u5173\u533a", count: 232 }, { name: "\u5bbd\u57ce\u533a", count: 198 }, { name: "\u4e8c\u9053\u533a", count: 168 }, { name: "\u7eff\u56ed\u533a", count: 142 }, { name: "\u51c0\u6708\u533a", count: 86 }],
  },
  "foshan-salon-tony": {
    name: "\u4f5b\u5c71",
    count: 1456,
    districts: [{ name: "\u5357\u6d77\u533a", count: 286 }, { name: "\u987a\u5fb7\u533a", count: 248 }, { name: "\u7985\u57ce\u533a", count: 212 }, { name: "\u4e09\u6c34\u533a", count: 142 }, { name: "\u9ad8\u660e\u533a", count: 96 }],
  },
  "tj-salon-tony": {
    name: "\u5929\u6d25",
    count: 1342,
    districts: [{ name: "\u6ee8\u6d77\u65b0\u533a", count: 246 }, { name: "\u5357\u5f00\u533a", count: 168 }, { name: "\u6cb3\u897f\u533a", count: 156 }, { name: "\u6cb3\u5317\u533a", count: 142 }, { name: "\u6cb3\u4e1c\u533a", count: 128 }, { name: "\u7ea2\u6865\u533a", count: 98 }, { name: "\u548c\u5e73\u533a", count: 86 }, { name: "\u897f\u9752\u533a", count: 76 }, { name: "\u4e1c\u4e3d\u533a", count: 64 }, { name: "\u6d25\u5357\u533a", count: 58 }, { name: "\u5317\u8fb0\u533a", count: 52 }],
  },
  "fz-salon-tony": {
    name: "\u798f\u5dde",
    count: 1342,
    districts: [{ name: "\u9f13\u697c\u533a", count: 228 }, { name: "\u53f0\u6c5f\u533a", count: 196 }, { name: "\u4ed3\u5c71\u533a", count: 168 }, { name: "\u664b\u5b89\u533a", count: 142 }, { name: "\u9a6c\u5c3e\u533a", count: 96 }, { name: "\u957f\u4e50\u533a", count: 72 }, { name: "\u798f\u6e05\u5e02", count: 56 }],
  },
  "cs-salon-tony": {
    name: "\u957f\u6c99",
    count: 1234,
    districts: [{ name: "\u5cb3\u9e93\u533a", count: 242 }, { name: "\u96e8\u82b1\u533a", count: 228 }, { name: "\u8299\u84c9\u533a", count: 196 }, { name: "\u5929\u5fc3\u533a", count: 168 }, { name: "\u5f00\u798f\u533a", count: 156 }, { name: "\u671b\u57ce\u533a", count: 98 }, { name: "\u957f\u6c99\u53bf", count: 86 }, { name: "\u6d4f\u9633\u5e02", count: 42 }, { name: "\u5b81\u4e61\u5e02", count: 32 }],
  },
  "gy-salon-tony": {
    name: "\u8d35\u9633",
    count: 1234,
    districts: [{ name: "\u5357\u660e\u533a", count: 228 }, { name: "\u4e91\u5ca9\u533a", count: 196 }, { name: "\u89c2\u5c71\u6e56\u533a", count: 168 }, { name: "\u82b1\u6eaa\u533a", count: 142 }, { name: "\u767d\u4e91\u533a", count: 112 }, { name: "\u4e4c\u5f53\u533a", count: 86 }],
  },
  "ty-salon-tony": {
    name: "\u592a\u539f",
    count: 1234,
    districts: [{ name: "\u5c0f\u5e97\u533a", count: 246 }, { name: "\u8fce\u6cfd\u533a", count: 198 }, { name: "\u674f\u82b1\u5cad\u533a", count: 168 }, { name: "\u4e07\u67cf\u6797\u533a", count: 142 }, { name: "\u664b\u6e90\u533a", count: 96 }, { name: "\u5c16\u8349\u576a\u533a", count: 72 }],
  },
  "wenzhou-salon-tony": {
    name: "\u6e29\u5dde",
    count: 1234,
    districts: [{ name: "\u9e7f\u57ce\u533a", count: 246 }, { name: "\u74ef\u6d77\u533a", count: 196 }, { name: "\u9f99\u6e7e\u533a", count: 142 }, { name: "\u4e50\u6e05\u5e02", count: 96 }, { name: "\u745e\u5b89\u5e02", count: 86 }],
  },
  "nanchang-salon-tony": {
    name: "\u5357\u660c",
    count: 1234,
    districts: [{ name: "\u7ea2\u8c37\u6ee9\u533a", count: 246 }, { name: "\u9752\u5c71\u6e56\u533a", count: 198 }, { name: "\u897f\u6e56\u533a", count: 168 }, { name: "\u4e1c\u6e56\u533a", count: 142 }, { name: "\u65b0\u5efa\u533a", count: 96 }],
  },
  "sy-salon-tony": {
    name: "\u6c88\u9633",
    count: 1098,
    districts: [{ name: "\u548c\u5e73\u533a", count: 186 }, { name: "\u6c88\u6cb3\u533a", count: 168 }, { name: "\u94c1\u897f\u533a", count: 154 }, { name: "\u5927\u4e1c\u533a", count: 132 }, { name: "\u7687\u59d1\u533a", count: 126 }, { name: "\u6d51\u5357\u533a", count: 108 }, { name: "\u4e8e\u6d2a\u533a", count: 72 }, { name: "\u6c88\u5317\u65b0\u533a", count: 56 }, { name: "\u82cf\u5bb6\u5c6f\u533a", count: 42 }],
  },
  "wlmq-salon-tony": {
    name: "\u4e4c\u9c81\u6728\u9f50",
    count: 1027,
    districts: [{ name: "\u5929\u5c71\u533a", count: 168 }, { name: "\u6c99\u4f9d\u5df4\u514b\u533a", count: 142 }, { name: "\u9ad8\u65b0\u533a", count: 128 }, { name: "\u6c34\u78e8\u6c9f\u533a", count: 98 }, { name: "\u7c73\u4e1c\u533a", count: 86 }, { name: "\u5934\u5c6f\u6cb3\u533a", count: 72 }, { name: "\u65b0\u5e02\u533a", count: 68 }],
  },
  "lz-salon-tony": {
    name: "\u5170\u5dde",
    count: 1023,
    districts: [{ name: "\u57ce\u5173\u533a", count: 286 }, { name: "\u4e03\u91cc\u6cb3\u533a", count: 168 }, { name: "\u897f\u56fa\u533a", count: 142 }, { name: "\u5b89\u5b81\u533a", count: 112 }, { name: "\u7ea2\u53e4\u533a", count: 68 }, { name: "\u6986\u4e2d\u53bf", count: 42 }],
  },
  "yantai-salon-tony": {
    name: "\u70df\u53f0",
    count: 1023,
    districts: [{ name: "\u829d\u7f58\u533a", count: 196 }, { name: "\u798f\u5c71\u533a", count: 142 }, { name: "\u83b1\u5c71\u533a", count: 128 }, { name: "\u725f\u5e73\u533a", count: 96 }, { name: "\u84ec\u83b1\u533a", count: 68 }],
  },
  "quanzhou-salon-tony": {
    name: "\u6cc9\u5dde",
    count: 1023,
    districts: [{ name: "\u4e30\u6cfd\u533a", count: 186 }, { name: "\u664b\u6c5f\u5e02", count: 168 }, { name: "\u9ca4\u57ce\u533a", count: 142 }, { name: "\u6d1b\u6c5f\u533a", count: 96 }, { name: "\u77f3\u72ee\u5e02", count: 72 }],
  },
  "weifang-salon-tony": {
    name: "\u6f4d\u574a",
    count: 968,
    districts: [{ name: "\u594e\u6587\u533a", count: 186 }, { name: "\u6f4d\u57ce\u533a", count: 142 }, { name: "\u5bd2\u4ead\u533a", count: 96 }, { name: "\u574a\u5b50\u533a", count: 72 }, { name: "\u5bff\u5149\u5e02", count: 52 }],
  },
  "dali-salon-tony": {
    name: "\u5927\u7406",
    count: 967,
    districts: [{ name: "\u5927\u7406\u5e02", count: 246 }, { name: "\u7965\u4e91\u53bf", count: 128 }, { name: "\u5bbe\u5ddd\u53bf", count: 96 }, { name: "\u5f25\u6e21\u53bf", count: 82 }, { name: "\u5dcd\u5c71\u53bf", count: 68 }, { name: "\u6d31\u6e90\u53bf", count: 56 }, { name: "\u5251\u5ddd\u53bf", count: 42 }],
  },
  "cz-salon-tony": {
    name: "\u5e38\u5dde",
    count: 912,
    districts: [{ name: "\u6b66\u8fdb\u533a", count: 186 }, { name: "\u65b0\u5317\u533a", count: 164 }, { name: "\u5929\u5b81\u533a", count: 152 }, { name: "\u949f\u697c\u533a", count: 131 }, { name: "\u91d1\u575b\u533a", count: 96 }, { name: "\u6ea7\u9633\u5e02", count: 86 }, { name: "\u7ecf\u5f00\u533a", count: 60 }, { name: "\u6f15\u6865\u9547", count: 37 }],
  },
  "xm-salon-tony": {
    name: "\u53a6\u95e8",
    count: 856,
    districts: [{ name: "\u601d\u660e\u533a", count: 238 }, { name: "\u6e56\u91cc\u533a", count: 196 }, { name: "\u96c6\u7f8e\u533a", count: 138 }, { name: "\u6d77\u6ca7\u533a", count: 98 }, { name: "\u540c\u5b89\u533a", count: 86 }, { name: "\u7fd4\u5b89\u533a", count: 62 }],
  },
  "hk-salon-tony": {
    name: "\u6d77\u53e3",
    count: 856,
    districts: [{ name: "\u9f99\u534e\u533a", count: 196 }, { name: "\u7f8e\u5170\u533a", count: 168 }, { name: "\u743c\u5c71\u533a", count: 142 }, { name: "\u79c0\u82f1\u533a", count: 98 }],
  },
  "shaoxing-salon-tony": {
    name: "\u7ecd\u5174",
    count: 856,
    districts: [{ name: "\u8d8a\u57ce\u533a", count: 196 }, { name: "\u67ef\u6865\u533a", count: 142 }, { name: "\u4e0a\u865e\u533a", count: 96 }, { name: "\u8bf8\u66a8\u5e02", count: 72 }],
  },
  "taizhou-salon-tony": {
    name: "\u53f0\u5dde",
    count: 856,
    districts: [{ name: "\u6912\u6c5f\u533a", count: 186 }, { name: "\u9ec4\u5ca9\u533a", count: 142 }, { name: "\u8def\u6865\u533a", count: 128 }, { name: "\u6e29\u5cad\u5e02", count: 86 }],
  },
  "zhuhai-salon-tony": {
    name: "\u73e0\u6d77",
    count: 856,
    districts: [{ name: "\u9999\u6d32\u533a", count: 196 }, { name: "\u6597\u95e8\u533a", count: 142 }, { name: "\u91d1\u6e7e\u533a", count: 96 }],
  },
  "huizhou-salon-tony": {
    name: "\u60e0\u5dde",
    count: 856,
    districts: [{ name: "\u60e0\u57ce\u533a", count: 196 }, { name: "\u60e0\u9633\u533a", count: 142 }, { name: "\u535a\u7f57\u53bf", count: 96 }, { name: "\u60e0\u4e1c\u53bf", count: 72 }],
  },
  "xuzhou-salon-tony": {
    name: "\u5f90\u5dde",
    count: 856,
    districts: [{ name: "\u9f13\u697c\u533a", count: 186 }, { name: "\u4e91\u9f99\u533a", count: 142 }, { name: "\u6cc9\u5c71\u533a", count: 128 }, { name: "\u94dc\u5c71\u533a", count: 96 }, { name: "\u8d3e\u6c6a\u533a", count: 72 }],
  },
  "jinhua-salon-tony": {
    name: "\u91d1\u534e",
    count: 786,
    districts: [{ name: "\u5a7a\u57ce\u533a", count: 186 }, { name: "\u91d1\u4e1c\u533a", count: 142 }, { name: "\u4e49\u4e4c\u5e02", count: 168 }, { name: "\u4e1c\u9633\u5e02", count: 72 }],
  },
  "st-salon-tony": {
    name: "\u6c55\u5934",
    count: 786,
    districts: [{ name: "\u91d1\u5e73\u533a", count: 168 }, { name: "\u9f99\u6e56\u533a", count: 142 }, { name: "\u6f84\u6d77\u533a", count: 96 }, { name: "\u6f6e\u9633\u533a", count: 86 }],
  },
  "liuzhou-salon-tony": {
    name: "\u67f3\u5dde",
    count: 786,
    districts: [{ name: "\u57ce\u4e2d\u533a", count: 168 }, { name: "\u9c7c\u5cf0\u533a", count: 142 }, { name: "\u67f3\u5357\u533a", count: 128 }, { name: "\u67f3\u5317\u533a", count: 96 }, { name: "\u67f3\u6c5f\u533a", count: 72 }],
  },
  "linyi-salon-tony": {
    name: "\u4e34\u6c82",
    count: 768,
    districts: [{ name: "\u5170\u5c71\u533a", count: 186 }, { name: "\u7f57\u5e84\u533a", count: 142 }, { name: "\u6cb3\u4e1c\u533a", count: 112 }, { name: "\u6c82\u6c34\u53bf", count: 56 }],
  },
  "baoding-salon-tony": {
    name: "\u4fdd\u5b9a",
    count: 768,
    districts: [{ name: "\u7ade\u79c0\u533a", count: 142 }, { name: "\u83b2\u6c60\u533a", count: 128 }, { name: "\u6ee1\u57ce\u533a", count: 96 }, { name: "\u6e05\u82d1\u533a", count: 72 }, { name: "\u5f90\u6c34\u533a", count: 56 }],
  },
  "hhht-salon-tony": {
    name: "\u547c\u548c\u6d69\u7279",
    count: 756,
    districts: [{ name: "\u8d5b\u7f55\u533a", count: 168 }, { name: "\u65b0\u57ce\u533a", count: 142 }, { name: "\u56de\u6c11\u533a", count: 126 }, { name: "\u7389\u6cc9\u533a", count: 98 }, { name: "\u571f\u9ed8\u7279\u5de6\u65d7", count: 42 }],
  },
  "jiaxing-salon-tony": {
    name: "\u5609\u5174",
    count: 756,
    districts: [{ name: "\u5357\u6e56\u533a", count: 186 }, { name: "\u79c0\u6d32\u533a", count: 142 }, { name: "\u6d77\u5b81\u5e02", count: 86 }, { name: "\u6850\u4e61\u5e02", count: 72 }],
  },
  "zibo-salon-tony": {
    name: "\u6dc4\u535a",
    count: 712,
    districts: [{ name: "\u5f20\u5e97\u533a", count: 168 }, { name: "\u4e34\u6dc4\u533a", count: 96 }, { name: "\u6dc4\u5ddd\u533a", count: 86 }, { name: "\u535a\u5c71\u533a", count: 72 }],
  },
  "jilin-salon-tony": {
    name: "\u5409\u6797",
    count: 698,
    districts: [{ name: "\u8239\u8425\u533a", count: 142 }, { name: "\u660c\u9091\u533a", count: 128 }, { name: "\u9f99\u6f6d\u533a", count: 96 }, { name: "\u4e30\u6ee1\u533a", count: 72 }, { name: "\u6866\u7538\u5e02", count: 38 }],
  },
  "dt-salon-tony": {
    name: "\u5927\u540c",
    count: 689,
    districts: [{ name: "\u5e73\u57ce\u533a", count: 186 }, { name: "\u4e91\u5188\u533a", count: 142 }, { name: "\u65b0\u8363\u533a", count: 86 }, { name: "\u4e91\u5dde\u533a", count: 68 }],
  },
  "bt-salon-tony": {
    name: "\u5305\u5934",
    count: 612,
    districts: [{ name: "\u6606\u90fd\u4ed1\u533a", count: 142 }, { name: "\u9752\u5c71\u533a", count: 128 }, { name: "\u4e1c\u6cb3\u533a", count: 96 }, { name: "\u4e5d\u539f\u533a", count: 68 }, { name: "\u7a00\u571f\u9ad8\u65b0\u533a", count: 52 }],
  },
  "yq-salon-tony": {
    name: "\u94f6\u5ddd",
    count: 612,
    districts: [{ name: "\u5174\u5e86\u533a", count: 168 }, { name: "\u91d1\u51e4\u533a", count: 142 }, { name: "\u897f\u590f\u533a", count: 112 }],
  },
  "weihai-salon-tony": {
    name: "\u5a01\u6d77",
    count: 612,
    districts: [{ name: "\u73af\u7fe0\u533a", count: 142 }, { name: "\u6587\u767b\u533a", count: 96 }, { name: "\u8363\u6210\u5e02", count: 68 }, { name: "\u4e73\u5c71\u5e02", count: 42 }],
  },
  "huzhou-salon-tony": {
    name: "\u6e56\u5dde",
    count: 612,
    districts: [{ name: "\u5434\u5174\u533a", count: 168 }, { name: "\u5357\u6d54\u533a", count: 128 }, { name: "\u5fb7\u6e05\u53bf", count: 52 }],
  },
  "zhangzhou-salon-tony": {
    name: "\u6f33\u5dde",
    count: 612,
    districts: [{ name: "\u8297\u57ce\u533a", count: 142 }, { name: "\u9f99\u6587\u533a", count: 96 }, { name: "\u9f99\u6d77\u533a", count: 72 }],
  },
  "zs-salon-tony": {
    name: "\u4e2d\u5c71",
    count: 612,
    districts: [{ name: "\u77f3\u5c90\u8857\u9053", count: 142 }, { name: "\u4e1c\u533a\u8857\u9053", count: 128 }, { name: "\u5c0f\u6984\u9547", count: 96 }, { name: "\u53e4\u9547\u9547", count: 72 }],
  },
  "zhanjiang-salon-tony": {
    name: "\u6e5b\u6c5f",
    count: 612,
    districts: [{ name: "\u8d64\u574e\u533a", count: 142 }, { name: "\u971e\u5c71\u533a", count: 128 }, { name: "\u9ebb\u7ae0\u533a", count: 96 }, { name: "\u5ec9\u6c5f\u5e02", count: 52 }],
  },
  "wx-salon-tony": {
    name: "\u65e0\u9521",
    count: 592,
    districts: [{ name: "\u6881\u6eaa\u533a", count: 128 }, { name: "\u6ee8\u6e56\u533a", count: 112 }, { name: "\u9521\u5c71\u533a", count: 96 }, { name: "\u60e0\u5c71\u533a", count: 78 }, { name: "\u65b0\u5434\u533a", count: 72 }, { name: "\u6c5f\u9634\u5e02", count: 58 }, { name: "\u5b9c\u5174\u5e02", count: 48 }],
  },
  "xn-salon-tony": {
    name: "\u897f\u5b81",
    count: 586,
    districts: [{ name: "\u57ce\u897f\u533a", count: 142 }, { name: "\u57ce\u4e2d\u533a", count: 128 }, { name: "\u57ce\u4e1c\u533a", count: 112 }, { name: "\u57ce\u5317\u533a", count: 96 }],
  },
  "taian-salon-tony": {
    name: "\u6cf0\u5b89",
    count: 586,
    districts: [{ name: "\u6cf0\u5c71\u533a", count: 142 }, { name: "\u5cb1\u5cb3\u533a", count: 96 }, { name: "\u65b0\u6cf0\u5e02", count: 52 }],
  },
  "ganzhou-salon-tony": {
    name: "\u8d63\u5dde",
    count: 586,
    districts: [{ name: "\u7ae0\u8d21\u533a", count: 142 }, { name: "\u5357\u5eb7\u533a", count: 96 }, { name: "\u8d63\u53bf\u533a", count: 72 }],
  },
  "yichang-salon-tony": {
    name: "\u5b9c\u660c",
    count: 586,
    districts: [{ name: "\u897f\u9675\u533a", count: 142 }, { name: "\u4f0d\u5bb6\u5c97\u533a", count: 96 }, { name: "\u5937\u9675\u533a", count: 86 }, { name: "\u70b9\u519b\u533a", count: 42 }],
  },
  "sya-salon-tony": {
    name: "\u4e09\u4e9a",
    count: 526,
    districts: [{ name: "\u5409\u9633\u533a", count: 128 }, { name: "\u5929\u6daf\u533a", count: 112 }, { name: "\u6d77\u68e0\u533a", count: 86 }, { name: "\u5d16\u5dde\u533a", count: 52 }],
  },
  "maoming-salon-tony": {
    name: "\u8302\u540d",
    count: 512,
    districts: [{ name: "\u8302\u5357\u533a", count: 142 }, { name: "\u7535\u767d\u533a", count: 96 }, { name: "\u9ad8\u5dde\u5e02", count: 52 }],
  },
  "as-salon-tony": {
    name: "\u978d\u5c71",
    count: 512,
    districts: [{ name: "\u94c1\u4e1c\u533a", count: 112 }, { name: "\u94c1\u897f\u533a", count: 96 }, { name: "\u7acb\u5c71\u533a", count: 86 }, { name: "\u5343\u5c71\u533a", count: 42 }],
  },
  "rizhao-salon-tony": {
    name: "\u65e5\u7167",
    count: 486,
    districts: [{ name: "\u4e1c\u6e2f\u533a", count: 142 }, { name: "\u5c9a\u5c71\u533a", count: 86 }, { name: "\u4e94\u83b2\u53bf", count: 42 }],
  },
  "jieyang-salon-tony": {
    name: "\u63ed\u9633",
    count: 486,
    districts: [{ name: "\u6995\u57ce\u533a", count: 142 }, { name: "\u63ed\u4e1c\u533a", count: 86 }, { name: "\u666e\u5b81\u5e02", count: 72 }],
  },
  "dongying-salon-tony": {
    name: "\u4e1c\u8425",
    count: 386,
    districts: [{ name: "\u4e1c\u8425\u533a", count: 96 }, { name: "\u6cb3\u53e3\u533a", count: 52 }, { name: "\u57a6\u5229\u533a", count: 42 }],
  },
  "lijiang-salon-tony": {
    name: "\u4e3d\u6c5f",
    count: 386,
    districts: [{ name: "\u53e4\u57ce\u533a", count: 142 }, { name: "\u7389\u9f99\u53bf", count: 86 }, { name: "\u6c38\u80dc\u53bf", count: 42 }],
  },
  "lasa-salon-tony": {
    name: "\u62c9\u8428",
    count: 286,
    districts: [{ name: "\u57ce\u5173\u533a", count: 86 }, { name: "\u5806\u9f99\u5fb7\u5e86\u533a", count: 48 }, { name: "\u8fbe\u5b5c\u533a", count: 32 }],
  },
  "zhoushan-salon-tony": {
    name: "\u821f\u5c71",
    count: 286,
    districts: [{ name: "\u5b9a\u6d77\u533a", count: 96 }, { name: "\u666e\u9640\u533a", count: 72 }],
  }
};

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

export function generateCityPage(slug: string): string {
  const city = CITIES[slug];
  if (!city) return '';

  const cityName = city.name;
  const sortedDistricts = [...city.districts].sort((a, b) => b.count - a.count);
  const districtCards = sortedDistricts.map(d =>
    `<div class="d-card">
      <div class="d-name">${escapeHtml(d.name)}</div>
      <div class="d-count">${d.count}</div>
    </div>`
  ).join('');

  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>${cityName}美发圈 - 安柯耳 Airaquas</title>
<meta name="description" content="${cityName}美发店名录 · ${city.count}家合作沙龙 · 安柯耳城市美发圈"/>
<link rel="canonical" href="https://airaquas.hair/${slug}"/>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,BlinkMacSystemFont,'Noto Sans SC','PingFang SC','Microsoft YaHei','Hiragino Sans GB',sans-serif;background:#0b0d16;color:#d0d0d8;line-height:1.6;-webkit-font-smoothing:antialiased}
.wrap{max-width:600px;margin:0 auto;padding:0 16px 80px}
.hd{display:flex;align-items:center;padding:14px 0;position:sticky;top:0;background:rgba(11,13,22,.92);backdrop-filter:blur(12px);z-index:100}
.hd-left{display:flex;align-items:center;gap:10px}
.back{display:inline-flex;align-items:center;gap:4px;padding:6px 12px;border-radius:8px;color:rgba(255,255,255,.4);text-decoration:none;font-size:13px;transition:all .2s}
.back:hover{color:#d0d0d8;background:rgba(255,255,255,.04)}
.lg{font-size:13px;font-weight:600;color:#e8e4dc;letter-spacing:.5px}
.city-badge{display:inline-block;padding:4px 12px;border-radius:12px;font-size:11px;background:rgba(123,193,255,.08);color:#7bc1ff;margin-bottom:4px}
.title-area{margin:24px 0 4px}
h1{font-size:26px;color:#e8e4dc;font-weight:700;margin:0}
.sub{color:rgba(255,255,255,.35);font-size:13px;margin:4px 0 20px}
.summary{display:flex;gap:12px;margin-bottom:24px;padding:16px;background:rgba(255,255,255,.02);border:1px solid rgba(255,255,255,.04);border-radius:14px}
.s-item{flex:1;text-align:center}
.s-val{font-size:22px;font-weight:700;color:#7bc1ff}
.s-lbl{font-size:11px;color:rgba(255,255,255,.3);margin-top:2px}
.section-title{font-size:14px;font-weight:500;color:rgba(255,255,255,.4);margin-bottom:10px;letter-spacing:.04em}
.d-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}
.d-card{display:flex;align-items:center;justify-content:space-between;padding:10px 14px;border-radius:10px;background:rgba(255,255,255,.02);border:1px solid rgba(255,255,255,.04);transition:all .2s}
.d-card:hover{background:rgba(255,255,255,.04);border-color:rgba(123,193,255,.1)}
.d-name{font-size:13px;color:#d0d0d8}
.d-count{font-size:13px;font-weight:600;color:#7bc1ff}
/* Shop list */
.shop-card{display:flex;gap:10px;padding:12px 14px;border-radius:10px;background:rgba(255,255,255,.02);border:1px solid rgba(255,255,255,.04);margin-bottom:8px;transition:.2s;align-items:center}
.shop-card:hover{border-color:rgba(123,193,255,.12);transform:translateY(-1px)}
.shop-idx{width:22px;height:22px;min-width:22px;border-radius:6px;background:rgba(123,193,255,.08);color:#7bc1ff;font-size:10px;font-weight:700;display:flex;align-items:center;justify-content:center;flex-shrink:0}
.shop-body{flex:1;min-width:0}
.shop-name{font-size:14px;font-weight:600;color:#e8e4dc;line-height:1.4;margin-bottom:3px}
.shop-badge{display:inline-block;font-size:9px;padding:1px 6px;border-radius:3px;background:rgba(123,193,255,.06);color:#7bc1ff;margin-left:6px;vertical-align:middle}
.shop-addr{font-size:11px;color:rgba(255,255,255,.35);line-height:1.4;margin-bottom:4px}
.shop-actions{display:flex;gap:6px;flex-wrap:wrap}
.shop-tel{display:inline-flex;align-items:center;gap:3px;padding:4px 10px;border-radius:5px;font-size:11px;background:rgba(123,193,255,.06);color:#7bc1ff;text-decoration:none;transition:.2s}
.shop-tel:hover{background:rgba(123,193,255,.12)}
.shop-map{display:inline-flex;align-items:center;gap:3px;padding:4px 10px;border-radius:5px;font-size:11px;background:rgba(255,255,255,.03);color:rgba(255,255,255,.35);text-decoration:none;transition:.2s}
.shop-map:hover{background:rgba(255,255,255,.06)}
.loading{text-align:center;padding:24px;color:rgba(255,255,255,.25);font-size:13px}
.no-data{text-align:center;padding:32px;color:rgba(255,255,255,.25);font-size:13px;border:1px dashed rgba(255,255,255,.04);border-radius:10px}
.cta{display:block;text-align:center;padding:28px;margin-top:32px;background:radial-gradient(ellipse at center,rgba(123,193,255,.04),transparent 70%);border-radius:16px;text-decoration:none}
.cta h3{color:#e8e4dc;font-size:15px;margin-bottom:6px}
.cta p{color:rgba(255,255,255,.3);font-size:12px}
.cta-btn{display:inline-block;padding:10px 28px;margin-top:12px;background:linear-gradient(135deg,#7bc1ff,#4a90d9);color:#0b0d16;border-radius:8px;font-size:14px;font-weight:600}
@media(max-width:480px){.d-grid{grid-template-columns:1fr}}
</style>
</head>
<body><div class="wrap">
<div class="hd">
<div class="hd-left">
<a class="back" href="/tony-cities">&larr; 返回城市列表</a>
<div class="lg">安柯耳</div>
</div>
</div>
<div class="city-badge">📍 ${cityName}</div>
<div class="title-area">
<h1>${cityName}美发圈</h1>
<p class="sub">Tony老师在店 · ${city.count}家合作美发店 · 覆盖${sortedDistricts.length}个区</p>
</div>
<div class="summary">
<div class="s-item"><div class="s-val">${city.count}</div><div class="s-lbl">合作美发店</div></div>
<div class="s-item"><div class="s-val">${sortedDistricts.length}</div><div class="s-lbl">覆盖区域</div></div>
<div class="s-item"><div class="s-val">${cityName}</div><div class="s-lbl">运营城市</div></div>
</div>
<div class="section-title">📍 区域分布</div>
<div class="d-grid">
${districtCards}
</div>
<div class="section-title" style="margin-top:20px">🏪 门店列表</div>
<div id="shopList"><div class="loading">加载门店数据...</div></div>
<script>
(function(){
var slug='${slug}';
fetch('/salon/data/'+slug+'.json')
.then(function(r){if(!r.ok)throw Error();return r.json()})
.then(function(shops){
  var el=document.getElementById('shopList');
  el.innerHTML=shops.map(function(s,i){
    return '<div class="shop-card"><div class="shop-idx">'+(i+1)+'</div><div class="shop-body"><div class="shop-name">'+s.name+'<span class="shop-badge">美发</span></div><div class="shop-addr">'+(s.address||'')+'</div><div class="shop-actions">'+(s.tel?'<a class="shop-tel" href="tel:'+s.tel+'">'+s.tel+'</a>':'')+'<a class="shop-map" href="https://uri.amap.com/search?keyword='+encodeURIComponent(s.name)+'&city='+encodeURIComponent(s.cityname||'')+'" target="_blank">地图</a></div></div></div>';
  }).join('')||'<div class="no-data">暂无门店数据</div>';
})
.catch(function(){document.getElementById('shopList').innerHTML='<div class="no-data">门店数据待更新</div>'});
})();
</script>
<a class="cta" href="/detect"><h3>AI头皮检测 · 合作沙龙专属</h3><p>先检测再选店，科学护理更有效</p><div class="cta-btn">开始AI检测 &rarr;</div></a>
</div></body></html>`;
}

export function generateCityListHtml(): string {
  const major = [
  '<a href="/tony/cd-salon-tony" class="city"><span class="cname">成都</span><span class="ccount">4020</span></a>',
  '<a href="/tony/cq-salon-tony" class="city"><span class="cname">重庆</span><span class="ccount">3060</span></a>',
  '<a href="/tony/wh-salon-tony" class="city"><span class="cname">武汉</span><span class="ccount">2899</span></a>',
  '<a href="/tony/hz-salon-tony" class="city"><span class="cname">杭州</span><span class="ccount">2777</span></a>',
  '<a href="/tony/nj-salon-tony" class="city"><span class="cname">南京</span><span class="ccount">2323</span></a>',
  '<a href="/tony/bj-salon-tony" class="city"><span class="cname">北京</span><span class="ccount">2193</span></a>',
  '<a href="/tony/sh-salon-tony" class="city"><span class="cname">上海</span><span class="ccount">2184</span></a>',
  '<a href="/tony/qd-salon-tony" class="city"><span class="cname">青岛</span><span class="ccount">2156</span></a>',
  '<a href="/tony/heb-salon-tony" class="city"><span class="cname">哈尔滨</span><span class="ccount">2112</span></a>',
  '<a href="/tony/xa-salon-tony" class="city"><span class="cname">西安</span><span class="ccount">2069</span></a>',
  '<a href="/tony/gzhu-salon-tony" class="city"><span class="cname">广州</span><span class="ccount">1955</span></a>',
  '<a href="/tony/gl-salon-tony" class="city"><span class="cname">桂林</span><span class="ccount">1945</span></a>',
  '<a href="/tony/jn-salon-tony" class="city"><span class="cname">济南</span><span class="ccount">1856</span></a>',
  '<a href="/tony/nb-salon-tony" class="city"><span class="cname">宁波</span><span class="ccount">1756</span></a>',
  '<a href="/tony/dl-salon-tony" class="city"><span class="cname">大连</span><span class="ccount">1689</span></a>',
  '<a href="/tony/dg-salon-tony" class="city"><span class="cname">东莞</span><span class="ccount">1689</span></a>',
  '<a href="/tony/su-salon-tony" class="city"><span class="cname">苏州</span><span class="ccount">1687</span></a>',
  '<a href="/tony/km-salon-tony" class="city"><span class="cname">昆明</span><span class="ccount">1678</span></a>',
  '<a href="/tony/hf-salon-tony" class="city"><span class="cname">合肥</span><span class="ccount">1568</span></a>',
  '<a href="/tony/zunyi-salon-tony" class="city"><span class="cname">遵义</span><span class="ccount">1568</span></a>',
  '<a href="/tony/szhen-salon-tony" class="city"><span class="cname">深圳</span><span class="ccount">1524</span></a>',
  '<a href="/tony/nn-salon-tony" class="city"><span class="cname">南宁</span><span class="ccount">1482</span></a>',
  '<a href="/tony/zz-salon-tony" class="city"><span class="cname">郑州</span><span class="ccount">1456</span></a>',
  '<a href="/tony/cc-salon-tony" class="city"><span class="cname">长春</span><span class="ccount">1456</span></a>',
  '<a href="/tony/foshan-salon-tony" class="city"><span class="cname">佛山</span><span class="ccount">1456</span></a>',
  '<a href="/tony/tj-salon-tony" class="city"><span class="cname">天津</span><span class="ccount">1342</span></a>',
  '<a href="/tony/fz-salon-tony" class="city"><span class="cname">福州</span><span class="ccount">1342</span></a>',
  '<a href="/tony/cs-salon-tony" class="city"><span class="cname">长沙</span><span class="ccount">1234</span></a>',
  '<a href="/tony/gy-salon-tony" class="city"><span class="cname">贵阳</span><span class="ccount">1234</span></a>',
  '<a href="/tony/ty-salon-tony" class="city"><span class="cname">太原</span><span class="ccount">1234</span></a>',
  '<a href="/tony/wenzhou-salon-tony" class="city"><span class="cname">温州</span><span class="ccount">1234</span></a>',
  '<a href="/tony/nanchang-salon-tony" class="city"><span class="cname">南昌</span><span class="ccount">1234</span></a>',
  '<a href="/tony/sy-salon-tony" class="city"><span class="cname">沈阳</span><span class="ccount">1098</span></a>',
  '<a href="/tony/wlmq-salon-tony" class="city"><span class="cname">乌鲁木齐</span><span class="ccount">1027</span></a>',
  '<a href="/tony/lz-salon-tony" class="city"><span class="cname">兰州</span><span class="ccount">1023</span></a>',
  '<a href="/tony/yantai-salon-tony" class="city"><span class="cname">烟台</span><span class="ccount">1023</span></a>',
  '<a href="/tony/quanzhou-salon-tony" class="city"><span class="cname">泉州</span><span class="ccount">1023</span></a>',
  ];
  const standard = [
  '<a href="/tony/weifang-salon-tony" class="city"><span class="cname">潍坊</span><span class="ccount">968</span></a>',
  '<a href="/tony/dali-salon-tony" class="city"><span class="cname">大理</span><span class="ccount">967</span></a>',
  '<a href="/tony/cz-salon-tony" class="city"><span class="cname">常州</span><span class="ccount">912</span></a>',
  '<a href="/tony/xm-salon-tony" class="city"><span class="cname">厦门</span><span class="ccount">856</span></a>',
  '<a href="/tony/hk-salon-tony" class="city"><span class="cname">海口</span><span class="ccount">856</span></a>',
  '<a href="/tony/shaoxing-salon-tony" class="city"><span class="cname">绍兴</span><span class="ccount">856</span></a>',
  '<a href="/tony/taizhou-salon-tony" class="city"><span class="cname">台州</span><span class="ccount">856</span></a>',
  '<a href="/tony/zhuhai-salon-tony" class="city"><span class="cname">珠海</span><span class="ccount">856</span></a>',
  '<a href="/tony/huizhou-salon-tony" class="city"><span class="cname">惠州</span><span class="ccount">856</span></a>',
  '<a href="/tony/xuzhou-salon-tony" class="city"><span class="cname">徐州</span><span class="ccount">856</span></a>',
  '<a href="/tony/jinhua-salon-tony" class="city"><span class="cname">金华</span><span class="ccount">786</span></a>',
  '<a href="/tony/st-salon-tony" class="city"><span class="cname">汕头</span><span class="ccount">786</span></a>',
  '<a href="/tony/liuzhou-salon-tony" class="city"><span class="cname">柳州</span><span class="ccount">786</span></a>',
  '<a href="/tony/linyi-salon-tony" class="city"><span class="cname">临沂</span><span class="ccount">768</span></a>',
  '<a href="/tony/baoding-salon-tony" class="city"><span class="cname">保定</span><span class="ccount">768</span></a>',
  '<a href="/tony/hhht-salon-tony" class="city"><span class="cname">呼和浩特</span><span class="ccount">756</span></a>',
  '<a href="/tony/jiaxing-salon-tony" class="city"><span class="cname">嘉兴</span><span class="ccount">756</span></a>',
  '<a href="/tony/zibo-salon-tony" class="city"><span class="cname">淄博</span><span class="ccount">712</span></a>',
  '<a href="/tony/jilin-salon-tony" class="city"><span class="cname">吉林</span><span class="ccount">698</span></a>',
  '<a href="/tony/dt-salon-tony" class="city"><span class="cname">大同</span><span class="ccount">689</span></a>',
  '<a href="/tony/bt-salon-tony" class="city"><span class="cname">包头</span><span class="ccount">612</span></a>',
  '<a href="/tony/yq-salon-tony" class="city"><span class="cname">银川</span><span class="ccount">612</span></a>',
  '<a href="/tony/weihai-salon-tony" class="city"><span class="cname">威海</span><span class="ccount">612</span></a>',
  '<a href="/tony/huzhou-salon-tony" class="city"><span class="cname">湖州</span><span class="ccount">612</span></a>',
  '<a href="/tony/zhangzhou-salon-tony" class="city"><span class="cname">漳州</span><span class="ccount">612</span></a>',
  '<a href="/tony/zs-salon-tony" class="city"><span class="cname">中山</span><span class="ccount">612</span></a>',
  '<a href="/tony/zhanjiang-salon-tony" class="city"><span class="cname">湛江</span><span class="ccount">612</span></a>',
  '<a href="/tony/wx-salon-tony" class="city"><span class="cname">无锡</span><span class="ccount">592</span></a>',
  '<a href="/tony/xn-salon-tony" class="city"><span class="cname">西宁</span><span class="ccount">586</span></a>',
  '<a href="/tony/taian-salon-tony" class="city"><span class="cname">泰安</span><span class="ccount">586</span></a>',
  '<a href="/tony/ganzhou-salon-tony" class="city"><span class="cname">赣州</span><span class="ccount">586</span></a>',
  '<a href="/tony/yichang-salon-tony" class="city"><span class="cname">宜昌</span><span class="ccount">586</span></a>',
  '<a href="/tony/sya-salon-tony" class="city"><span class="cname">三亚</span><span class="ccount">526</span></a>',
  '<a href="/tony/maoming-salon-tony" class="city"><span class="cname">茂名</span><span class="ccount">512</span></a>',
  '<a href="/tony/as-salon-tony" class="city"><span class="cname">鞍山</span><span class="ccount">512</span></a>',
  '<a href="/tony/rizhao-salon-tony" class="city"><span class="cname">日照</span><span class="ccount">486</span></a>',
  '<a href="/tony/jieyang-salon-tony" class="city"><span class="cname">揭阳</span><span class="ccount">486</span></a>',
  '<a href="/tony/dongying-salon-tony" class="city"><span class="cname">东营</span><span class="ccount">386</span></a>',
  '<a href="/tony/lijiang-salon-tony" class="city"><span class="cname">丽江</span><span class="ccount">386</span></a>',
  '<a href="/tony/lasa-salon-tony" class="city"><span class="cname">拉萨</span><span class="ccount">286</span></a>',
  '<a href="/tony/zhoushan-salon-tony" class="city"><span class="cname">舟山</span><span class="ccount">286</span></a>',
  ];
  const majorHtml = major.join('');
  const standardHtml = standard.join('');

  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>城市美发圈 - 安柯耳 Airaquas</title>
<meta name="description" content="覆盖全国78城92036+家合作美发店，AI头皮检测合作沙龙名录。"/>
<link rel="canonical" href="https://airaquas.hair/salon"/>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,BlinkMacSystemFont,'Noto Sans SC','PingFang SC','Microsoft YaHei','Hiragino Sans GB',sans-serif;background:#0b0d16;color:#d0d0d8;line-height:1.6;-webkit-font-smoothing:antialiased}
.wrap{max-width:600px;margin:0 auto;padding:0 16px 80px}
.hd{display:flex;align-items:center;padding:14px 0;position:sticky;top:0;background:rgba(11,13,22,.92);backdrop-filter:blur(12px);z-index:100}
.lg{font-size:15px;font-weight:700;color:#e8e4dc;letter-spacing:1px}
.lg span{color:#7bc1ff;font-size:10px;display:block;letter-spacing:2px}
.badge{display:inline-block;padding:3px 10px;border-radius:12px;font-size:10px;background:rgba(123,193,255,.08);color:#7bc1ff;margin-bottom:8px}
h1{font-size:22px;color:#e8e4dc;font-weight:600;margin-bottom:4px}
.sub{color:rgba(255,255,255,.35);font-size:13px;margin-bottom:20px}
.grp{margin-bottom:20px}
.grp-title{font-size:13px;font-weight:500;color:rgba(255,255,255,.4);margin-bottom:8px;letter-spacing:.04em}
.city-wrap{display:flex;flex-wrap:wrap;gap:6px}
.city{display:flex;align-items:center;gap:6px;padding:8px 12px;border-radius:10px;background:rgba(255,255,255,.02);border:1px solid rgba(255,255,255,.04);text-decoration:none;transition:all .2s}
.city:hover{background:rgba(255,255,255,.04);border-color:rgba(123,193,255,.12);transform:translateY(-1px)}
.cname{font-size:14px;color:#d8d8e0;font-weight:500}
.ccount{font-size:11px;color:rgba(255,255,255,.25);margin-left:auto}
.cta{display:block;text-align:center;padding:28px;margin-top:32px;background:radial-gradient(ellipse at center,rgba(123,193,255,.04),transparent 70%);border-radius:16px;text-decoration:none}
.cta h3{color:#e8e4dc;font-size:15px;margin-bottom:6px}
.cta p{color:rgba(255,255,255,.3);font-size:12px}
.cta-btn{display:inline-block;padding:10px 28px;margin-top:12px;background:linear-gradient(135deg,#7bc1ff,#4a90d9);color:#0b0d16;border-radius:8px;font-size:14px;font-weight:600}
@media(max-width:480px){.city{min-width:100%}}
</style>
</head>
<body><div class="wrap">
<div class="hd"><div class="lg">安柯耳<span>城市美发圈</span></div></div>
<div class="badge">🗺️ 合作美发店网络</div>
<h1>Tony 老师在店</h1>
<p class="sub">覆盖全国 78 个城市 · 92036+ 家合作美发店</p>
<div class="grp"><div class="grp-title">📍 重点城市</div><div class="city-wrap">${majorHtml}</div></div>
<div class="grp"><div class="grp-title">📍 全部城市</div><div class="city-wrap">${standardHtml}</div></div>
<a class="cta" href="/"><h3>AI 头皮检测 · 合作沙龙专属</h3><p>Tony 老师已入驻城市美发圈</p><div class="cta-btn">回到首页 &rarr;</div></a>
</div></body></html>`;
}
